# Generated by Django 3.2.10 on 2021-12-23 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_app', '0007_post_like_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_by_users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
