# Generated by Django 3.2.10 on 2021-12-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0010_rename_show_to_banner_post_is_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_by_users',
            new_name='users_liked',
        ),
    ]
